Auto-commit: 2025-04-19 10:36:58

diff --git a/install b/install
--- a/install
+++ b/install
@@ -23,10 +23,13 @@ if [ $? -ne 0 ]
     exit 1
 fi
 
-mkdir $REPO
-if [ $? -ne 0 ]
-    echo "$WARN unable to create \"$REPO\" directory"
-    exit 1
+test -d $REPO
+if [ $? -ne 0 ]; then
+    mkdir $REPO
+    if [ $? -ne 0 ]
+        echo "$WARN unable to create \"$REPO\" directory"
+        exit 1
+    fi
 fi
 
 systemctl enable --user autogit.target
